blog/article/views.py
import requests
from flask import Blueprint, render_template, request, url_for
from flask_login import login_required, current_user
from sqlalchemy.orm import joinedload
from werkzeug.exceptions import NotFound
from werkzeug.utils import redirect
from typing import Dict


from blog.extensions import db
from blog.forms.article import CreateArticleForm
from blog.models import Tag
from blog.models.article import Article
from blog.models.author import Author

article = Blueprint('article', __name__, url_prefix='/articles', static_folder='../static')


@article.route('/create/', methods=['GET'])
@login_required
def create_article_form():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]
    return render_template('articles/create.html', form=form)


@article.route('/create/', methods=['POST'])
@login_required
def create_article():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]
    if form.validate_on_submit():

        if not current_user.author:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            db.session.flush()
        else:
            author = current_user.author

        _article = Article(author_id=author.id, title=form.title.data.strip(), text=form.text.data.strip())

        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                _article.tag.append(tag)

        db.session.add(_article)
        db.session.commit()
        return redirect(url_for('article.get_article', pk=_article.id))
    return render_template('articles/create.html',
                           form=form,
                           )


@article.route('/', methods=['GET'])
def article_list():
    # call RPC method
    # count_articles: Dict = requests.get('http://127.0.0.1:5000/api/articles/event_get_count/').json()
    return render_template('articles/list.html',
                           articles=Article.query.all(),
                           )


@article.route('/<int:pk>')
def get_article(pk: int):
    try:
        selected_art = Article.query.filter_by(id=pk).options(joinedload(Article.tag)).one_or_none()
    except KeyError:
        raise NotFound(f'Article id {pk} is not found')
    return render_template('articles/details.html',
                           art=selected_art
                           )

@article.route('/tag/<int:pk>')
def tag_article_list(pk: int):
    try:
        tag = Tag.query.filter_by(id=pk).one_or_none()
    except KeyError:
        raise NotFound(f'Tag id {pk} is not found')
    articles = tag.article
    return render_template('tags/details.html',
                           articles=articles, tag_name=tag.name,
                           )


blog/author/views.py
from flask import render_template, Blueprint
from flask_login import login_required

from blog.models.author import Author

author = Blueprint('author', __name__, url_prefix='/authors', static_folder='../static')

@author.route('/')
# @login_required
def author_list():
    authors = Author.query.all()
    return render_template('authors/list.html',
                           authors=authors
                           )

blog/user/views.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user, login_user
from sqlalchemy.exc import IntegrityError

from werkzeug.exceptions import NotFound
from werkzeug.security import generate_password_hash

from blog.extensions import db
from blog.forms.user import UserRegisterForm
from blog.models.user import User

user = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@user.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('user.get_user', pk=current_user.id))
    form = UserRegisterForm(request.form)
    errors = []
    if request.method == 'POST' and form.validate_on_submit():

        if User.query.filter_by(username=form.username.data).count():
            form.username.errors.append('user name is not uniq')
            return render_template('users/register.html', form=form)

        _user = User(
            username=form.username.data,
            email=form.email.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            password=generate_password_hash(form.password.data),
        )

        db.session.add(_user)
        try:
            db.session.commit()
        except IntegrityError:
            errors.append('SQL Server Error ')
        else:
            login_user(_user)

    return render_template(
        'users/register.html',
        form=form,
        errors=errors,
    )


@user.route('/')
@login_required
def user_list():
    users = User.query.all()
    return render_template('users/list.html',
                           users=users
                           )


@user.route('/<int:pk>')
@login_required
def get_user(pk: int):
    # from blog.models.user import User
    selected_user = User.query.filter_by(id=pk).one_or_none()
    if not selected_user:
        raise NotFound(f'User id {pk} not found')

    return render_template(
        'users/details.html',
        user=selected_user,
    )

blog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block css %}
        <!-- Bootstrap CSS -->
        <link href="{{ url_for('static', filename = 'css/bootstrap.min.css') }}" rel="stylesheet">
    {% endblock %}
    <title>
        {% block title %} {% endblock %}
    </title>
</head>
<body>
{% include 'navbar.html' %}
<div class="container">
    {% block body %}{% endblock %}
</div>
{% block js %}
<!-- Optional JavaScript; choose one of the two! -->
<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="{{ url_for('static', filename = 'js/bootstrap.bundle.min.js') }}"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->
{% endblock %}
</body>
</html>


blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.user_list')}}">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('author.author_list')}}">Authors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('article.article_list')}}">Articles</a>
                </li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('article.create_article_form') }}">Create article</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout ({{ current_user.username }})</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.register') }}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                {% endif %}
                 <li class="nav-item">
                    <a class="nav-link" href="/api/swagger">Swagger</a>
                </li>
            </ul>
            <span class="navbar-text">
        Navbar text with an inline element
      </span>
        </div>
    </div>
</nav>