blog/models/article.py
from datetime import datetime

from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship

from blog.app import db
from blog.models.article_tag import article_tag_association_table


class Article(db.Model):
    __tablename__ = 'articles'

    id = db.Column(db.Integer, primary_key=True)
    author_id = db.Column(db.Integer, ForeignKey('authors.id'), nullable=False)
    title = db.Column(db.String(255))
    text = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    author = relationship('Author', back_populates='article')
    tag = relationship(
        "Tag",
        secondary=article_tag_association_table,
        back_populates="article",
    )

    def __init__(self, author_id, title, text):
        self.author_id = author_id
        self.title = title
        self.text = text

    def __str__(self):
        return self.title

blog/forms/article.py
import wtforms
from flask_wtf import FlaskForm
from wtforms import StringField, validators, PasswordField, SubmitField, TextAreaField, SelectMultipleField


class CreateArticleForm(FlaskForm):
    title = StringField("Title", [validators.DataRequired()])
    text = TextAreaField("Text", [validators.DataRequired()])
    submit = SubmitField("Submit")
    tags = SelectMultipleField("Tags", coerce=int)

blog/article/views.py
import requests
from flask import Blueprint, render_template, request, url_for
from flask_login import login_required, current_user
from sqlalchemy.orm import joinedload
from werkzeug.exceptions import NotFound
from werkzeug.utils import redirect
from typing import Dict


from blog.extensions import db
from blog.forms.article import CreateArticleForm
from blog.models import Tag
from blog.models.article import Article
from blog.models.author import Author

article = Blueprint('article', __name__, url_prefix='/articles', static_folder='../static')


@article.route('/create/', methods=['GET'])
@login_required
def create_article_form():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]
    return render_template('articles/create.html', form=form)


@article.route('/create/', methods=['POST'])
@login_required
def create_article():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]
    if form.validate_on_submit():

        if not current_user.author:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            db.session.flush()
        else:
            author = current_user.author

        _article = Article(author_id=author.id, title=form.title.data.strip(), text=form.text.data.strip())

        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                _article.tag.append(tag)

        db.session.add(_article)
        db.session.commit()
        return redirect(url_for('article.get_article', pk=_article.id))
    return render_template('articles/create.html',
                           form=form,
                           )


@article.route('/', methods=['GET'])
def article_list():
    # call RPC method
    # count_articles: Dict = requests.get('http://127.0.0.1:5000/api/articles/event_get_count/').json()
    return render_template('articles/list.html',
                           articles=Article.query.all(),
                           )


@article.route('/<int:pk>')
def get_article(pk: int):
    try:
        selected_art = Article.query.filter_by(id=pk).options(joinedload(Article.tag)).one_or_none()
    except KeyError:
        raise NotFound(f'Article id {pk} is not found')
    return render_template('articles/details.html',
                           art=selected_art
                           )

@article.route('/tag/<int:pk>')
def tag_article_list(pk: int):
    try:
        tag = Tag.query.filter_by(id=pk).one_or_none()
    except KeyError:
        raise NotFound(f'Tag id {pk} is not found')
    articles = tag.article
    return render_template('tags/details.html',
                           articles=articles, tag_name=tag.name,
                           )


blog/templates/articles/create.html
{% extends 'base.html' %}
{% from "macros/formhelpers.html" import render_field %}

{% block title %}
    Create article
{% endblock %}

{% block body %}
    {% if errors %}
        {% for error in errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    {% endif %}

    <form method="POST">
        {{ form.csrf_token }}
        {% for field in ['title','text', 'tags'] %}
            {{ render_field(form[field]) }}
        {% endfor %}

        {{ form.submit(class="btn btn-primary mb-3") }}
    </form>
{% endblock %}

blog/templates/articles/details.html
{% extends 'base.html' %}
{% block title %}
article_id
{% endblock %}

{% block body %}
<h1> Title: {{ art.title }} </h1>
<h2> author: {{ art.author.user.username }} </h2>

<div class="row">
    <div class="col-md-12">{{ art['text'] }}</div>
</div>

<div class="row">
    <div class="col-6">
        <div> Created at {{ art.created_at}}</div>
        <div> Updated at {{ art.updated_at}}</div>
    </div>
    <div class="col-6">
        {% for tag in art.tag %}
            <a href="{{ url_for('article.tag_article_list', pk = tag.id) }}"><span class="badge bg-success">{{ tag.name }}</span></a>
        {% endfor %}
    </div>
</div>

{% endblock %}

blog/templates/articles/list.html
{% extends 'base.html' %}
{% block title %}
Index Page
{% endblock %}


{% block body %}
<div class="row">
    <div class="col">
        <h1>Articles</h1>
        {% for article in articles %}
            <li><a href="{{ url_for('article.get_article', pk = article.id) }}">"{{ article.title }}" by {{ article.author.user.username }}</a></li>
        {% endfor %}
    </div>
</div>
{% endblock %}
